spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY'
    driver-class-name: org.hsqldb.jdbcDriver
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master-test.xml'
    contexts: test
  web:
    locale: en_EN
    locale-resolver: fixed
