spring:
  datasource:
    url: jdbc:mysql://localhost:3306/faceitlibrarytask?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master-dev.xml'
    contexts: dev